@startuml sequence_diagram_stringify_asm

' legend
'     Diagram for the stringify_asm module
'     JASM version v1.0.0
' end legend

participant MasterOfPuppets
participant MatchedObserver
participant ConsumerBuilder
participant CompleteConsumer
participant ProducerBuilder
participant ComposableProducer
participant GNUObjdumpDisassembler
participant ObjdumpParserManual
participant RemoveEmptyInstructions
participant ValidAddrObserver
participant Observer

MasterOfPuppets -> MatchedObserver : instantiate
MasterOfPuppets -> ConsumerBuilder : build(consumer_type=Complete, ...)
ConsumerBuilder -> CompleteConsumer : instantiate(regex_rule, matched_observer, ...)
MasterOfPuppets -> ProducerBuilder : build(file_type, assembly_style)
ProducerBuilder -> ComposableProducer : instantiate(disassembler, parser)
MasterOfPuppets -> CompleteConsumer : prepare_observers()
CompleteConsumer -> RemoveEmptyInstructions : add_observer()
CompleteConsumer -> ValidAddrObserver : add_observer()

MasterOfPuppets -> ComposableProducer : process_file(file, consumer)
opt file_type == binary
    ComposableProducer -> GNUObjdumpDisassembler : disassemble(file)
    GNUObjdumpDisassembler -> ComposableProducer : return assembly
end

ComposableProducer -> ObjdumpParserManual : parse(assembly, consumer)
ObjdumpParserManual -> CompleteConsumer : consume_instruction(inst)

loop for each instruction
    CompleteConsumer -> RemoveEmptyInstructions : observe_instruction(inst)
    RemoveEmptyInstructions -> CompleteConsumer : return observed_instruction

    CompleteConsumer -> ValidAddrObserver : observe_instruction(modified_inst)
    ValidAddrObserver -> CompleteConsumer : return observed_instruction
    loop for each Observer
        CompleteConsumer -> Observer : observe_instruction(modified_inst)
        Observer -> CompleteConsumer : return modified_inst
    end
end

CompleteConsumer -> MasterOfPuppets : return final_instruccion

@enduml
