[tool.poetry]
name = "src"
version = "0.6.0"
description = "Juli Asm regex generator"
authors = ["Julian Merida <julianmr97@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^7.4.0"
pyparsing = "^3.1.1"
pathlib = "^1.0.1"
logging = "^0.4.9.6"
argparse = "^1.4.0"
pyyaml = "^6.0.1"
radon = "^6.0.1"
pylint = "^2.17.5"
mypy = "^1.5.1"
bandit = "^1.7.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
