@startuml JASM_workflow

!theme plain

participant "Binario" as Binario
participant "Código\nAssembly" as Assembly
participant "Parser\nAssembly" as AsmParser
participant "Archivo de Reglas\n(JASM & YAML)" as Reglas
participant "Generador\nde Regex" as RegexGenerator
participant "Motor\nde regex" as Execution
participant "Patrones\nidentificados" as Patrones_identificados


alt Binario
Binario -> Assembly : Binario decompilado
Assembly -> AsmParser : Instrucciones assembly
else Assembly
Assembly -> AsmParser : Instrucciones assembly
end

AsmParser -> Execution: Instrucciones Assembly procesadas
Reglas -> RegexGenerator : Patrones JASM
RegexGenerator -> Execution: Regex
Execution -> Patrones_identificados: Resultados


@enduml
