name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*" # Trigger on version tags e.g., v1.0.0
  pull_request:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          python -m pip install --upgrade pip
          pip install pytest pytest-xdist poetry pyyaml

      - name: Install dependencies with poetry
        run: |
          echo "Installing dependencies with poetry ..."
          poetry install

      - name: Install project
        run: |
          echo "Installing project..."
          pip install -e .
      - name: Run tests
        run: |
          echo "Running tests..."
          poetry run sh ./run_tests.sh

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          poetry install

      - name: Build package
        run: |
          echo "Building package..."
          poetry build

  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'created'
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          echo "Publishing package to PyPI..."
          poetry publish --build
