name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Run tests
        run: |
          echo "Running tests..."
          apt install pytest pytest-xdist
          sh ./run_tests.sh

      - name: Build package
        run: |
          echo "Building package..."
          poetry build
