name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "Running tests..."
          sh ./run_tests.sh

      - name: Build package
        run: |
          echo "Building package..."
          poetry build
