name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          python -m pip install --upgrade pip
          pip install pytest pytest-xdist poetry pyyaml pytest-benchmark pytest-fail-slow

      - name: Install dependencies with poetry
        run: |
          echo "Installing dependencies with poetry ..."
          poetry install

      - name: Install project
        run: |
          echo "Installing project..."
          pip install -e .
      - name: Run tests
        run: |
          echo "Running tests..."
          poetry run sh ./run_tests.sh

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          poetry install

      - name: Build package
        run: |
          echo "Building package..."
          poetry build
