name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          python -m pip install --upgrade pip
          pip install pytest pytest-xdist poetry

      - name: Run tests
        run: |
          echo "Running tests..."
          poetry run sh ./run_tests.sh

      - name: Build package
        run: |
          echo "Building package..."
          poetry build
